[[constraint]]
  name = "github.com/buaazp/fasthttprouter"
  version = "0.1.1"

[[constraint]]
  branch = "master"
  name = "github.com/dchest/uniuri"

[[constraint]]
  branch = "master"
  name = "github.com/dutchcoders/go-clamd"

[[constraint]]
  name = "github.com/jmoiron/sqlx"
  version = "1.2.0"

[[constraint]]
  name = "github.com/kataras/go-sessions"
  version = "3.1.0"

[[constraint]]
  name = "github.com/lib/pq"
  version = "1.3.0"

[[constraint]]
  name = "github.com/mailru/easyjson"
  version = "0.7.0"

[[constraint]]
  name = "github.com/valyala/fasthttp"
  version = "20180529.0.0"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  name = "gopkg.in/h2non/bimg.v1"
  version = "1.0.19"

[[constraint]]
  branch = "master"
  name = "gopkg.in/kothar/go-backblaze.v0"

[prune]
  go-tests = true
  unused-packages = true
